swagger: "2.0"
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0
host: api.example.com
basePath: /v1
schemes:
  - https

paths:

  ##### Points

  /user-points/{user-id}:
    get:
      tags:
        - Points
      description: this returns points of the specific user
      operationId: getUserPoints

      consumes:
        - application/octet-stream

      parameters:
        - name: userId
          in: path
          type: string
          required: true

#  /registration:
#    post:
#      tags:
#        - User
#      description: this endpoint is for registering the user
#      operationId: registerUser
#
#      parameters:
#        - schema:
#            $ref: '#/definitions/user'
#          in: body
#          name: body
#          required: true
#      produces:
#         - application/json
#
#
#      responses:
#        '200':
#          description: successful registration
#          schema:
#            $ref: '#/definitions/response'
#        '401':
#          schema:
#            $ref: '#/definitions/response'
#        '500':
#          schema:
#            $ref: '#/definitions/response'
#      security:
#        - OAuth2:
#            - 'write:trans'



definitions:
  user:
    title: user
    type: object
    properties:
      firstname:
        type: string
        required: true
        example:
          "John"
      lastname:
        type: string
        required: true
        example:
          "Hannes"
      email:
        type: string
        required: true
        example:
          "Hannes"
      username:
        type: string
        required: true
        example:
          "user122"
      password:
        type: string
        minLength: 8
        maxLength: 32
        required: true
        example:
          "yuyu177"
      password_confirm:
        type: string
        minLength: 8
        maxLength: 36
        required: true
        example:
          "yuyu177"


  response:
    title: container for response data
    type: object
    properties:
      status:
        type: string
      details:
        type: string